# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cb4d324c6107a27c58e9a4a360733e5156021791f8a31807da7d9b3d5f76130ddda4e10a75f8cd55c346b40206ac26d8690973f7df0d285c0dfefd0f7a75db0

test:
  secret_key_base: 2fb327762592f55b470b8e35a03699089c32391dbb7ec5254190e3536b695bdb07faf157048849befe8fa80e63e08ed381d33f06662d34035572f79bf5bdd741

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
